### ISSUE TITLE
qemu submodules reference is not a tree

### ISSUE THREAD

**Issue by gabbla** [mdionisio/linuxlab2018#1]
When updating the submodules, the fetching of `quem` fails. Even the link in the repo results in 404.

```bash
git submodule update --init --recursive qemu
fatal: reference is not a tree: 04937070de58c577cda7bf3a41769ab96b124c22
Unable to checkout '04937070de58c577cda7bf3a41769ab96b124c22' in submodule path 'qemu'
```

**Comment by mdionisio** [comment]
I'm sorry I forget to push my last commit. For now you can go in qemu folder and do
`git checkout mytest`

I will fix it this night. Many thank's

**Comment by mdionisio** [comment]
fixed.
